### ISSUE TITLE
Thunderbolt 3 problem solved

### ISSUE THREAD

**Issue by le332313** [kumakumalina/Dell_G7_7588_OpenCore_Hackintosh#2]
https://github.com/flyfeng2002/FYQ-Hackintosh

This project solved  Thunderbolt 3 problem  can you use it to fix your EFI

**Comment by kumakumalina** [comment]
Thank you, I will check it!

**Comment by kumakumalina** [comment]
> https://github.com/flyfeng2002/FYQ-Hackintosh
> 
> This project solved Thunderbolt 3 problem can you use it to fix your EFI

![image](https://user-images.githubusercontent.com/59220499/102471512-db5d0080-4087-11eb-8a1b-16c3311dfead.png)
![image](https://user-images.githubusercontent.com/59220499/102471558-ed3ea380-4087-11eb-8926-59c7328522ca.png)
![image](https://user-images.githubusercontent.com/59220499/102471608-fc255600-4087-11eb-9368-bc3c69d99b7f.png)
Confirmed! It's worked xD
But I need time to test the stability and configure a bit with my AIO SSDT.
Will release with OC version 0.6.5.
Thank you again!

**Comment by le332313** [comment]
> > https://github.com/flyfeng2002/FYQ-Hackintosh
> > This project solved Thunderbolt 3 problem can you use it to fix your EFI
> 
> ![image](https://user-images.githubusercontent.com/59220499/102471512-db5d0080-4087-11eb-8a1b-16c3311dfead.png)
> ![image](https://user-images.githubusercontent.com/59220499/102471558-ed3ea380-4087-11eb-8926-59c7328522ca.png)
> ![image](https://user-images.githubusercontent.com/59220499/102471608-fc255600-4087-11eb-9368-bc3c69d99b7f.png)
> Confirmed! It's worked xD
> But I need time to test the stability and configure a bit with my AIO SSDT.
> Will release with OC version 0.6.5.
> Thank you again!

looking for to your new EFI and thank you for sharing your achievement，thanks a lot

**Comment by kumakumalina** [comment]
> > > https://github.com/flyfeng2002/FYQ-Hackintosh
> > > This project solved Thunderbolt 3 problem can you use it to fix your EFI
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/59220499/102471512-db5d0080-4087-11eb-8a1b-16c3311dfead.png)
> > ![image](https://user-images.githubusercontent.com/59220499/102471558-ed3ea380-4087-11eb-8926-59c7328522ca.png)
> > ![image](https://user-images.githubusercontent.com/59220499/102471608-fc255600-4087-11eb-9368-bc3c69d99b7f.png)
> > Confirmed! It's worked xD
> > But I need time to test the stability and configure a bit with my AIO SSDT.
> > Will release with OC version 0.6.5.
> > Thank you again!
> 
> looking for to your new EFI and thank you for sharing your achievement，thanks a lot

OC 0.6.5 updated ! Thunderbolt 3 port hotplug is okay now. Thank you one again!
