### ISSUE TITLE
screen problem

### ISSUE THREAD

**Issue by le332313** [kumakumalina/Dell_G7_7588_OpenCore_Hackintosh#3]
What is the model of the screen you replaced and what brand

**Comment by kumakumalina** [comment]
https://www.panelook.com/NV156FHM-N4B_BOE_15.6_LCM_overview_34862.html
NV156FHM from BOE

**Comment by le332313** [comment]
> https://www.panelook.com/NV156FHM-N4B_BOE_15.6_LCM_overview_34862.html
> NV156FHM from BOE

thanks
